#include "cvr.h"

void CVR_Initialize(void) {
    // (AVDD - AVSS)/2 is disconnected from the CVREF2O pin
    CVRCONbits.CVR2OE = 0;
    // CVREFIN is generated by the resistor network
    CVRCONbits.VREFSEL = 0;
    // Comparator voltage reference circuit is powered down
    CVRCONbits.CVREN = 0;
    // Voltage level is disconnected from then CVREF1O pin
    CVRCONbits.CVR1OE = 0;
    // CVRSRC/32 step-size
    CVRCONbits.CVRR = 0;
    // Comparator voltage reference source, CVRSRC = AVDD - AVSS
    CVRCONbits.CVRSS = 0;
    // CVREFIN = (CVRSRC/4) + (CVR[3:0]/32) x (CVRSRC)
    CVRCONbits.CVR = 0b000;
}

void CVR_ComparatorReference1Connection(bool connect) {
    // Voltage level is dis/connect at the CVREF1O pin
    CVRCONbits.CVR1OE = connect;
}

void CVR_ComparatorReference2Connection(bool connect) {
    // (AVDD - AVSS)/2 is dis/connect at the CVREF2O pin
    CVRCONbits.CVR2OE = connect;
}

void CVR_SetupComparator(void) {
    CVR_Initialize();
    CVR_SetReferenceVoltage(7); // ~ 1.54V
    CVR_ComparatorPowerUp();
}
